name: skin_tone_shop
description: A Flutter e-commerce app that recommends clothing based on users' skin tones with product aggregation from multiple retailers.
version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  url_launcher: ^6.1.10
  shared_preferences: ^2.1.0
  http: ^0.13.5
  cached_network_image: ^3.2.3
  intl: ^0.18.0
  vector_math: ^2.1.4
  image_picker: ^1.0.4
  camera: ^0.10.5+5
  path_provider: ^2.1.1
  palette_generator: ^0.3.3+3
  permission_handler: ^11.0.1
  image: ^4.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/